server:
  name: gin-gateway
  host: 0.0.0.0
  port: 41000
  mode: release # debug / release

proxy:
  timeout_ms: "3000ms"
  keep_alive: true

logging:
  level: info
  access_log: true

register:
  type: nacos
  endpoints:
    - 127.0.0.1:2379
  namespace: public
  timeout: 5000
